global class NxlConstants {
	static global string GENERAL_SETTINGS = 'general_settings';
    static global string SECURE_ENTITIES = 'secure_entities';
    static global string USER_ATTRIBUTES = 'user_attributes';
    static global string TRIGGERS = 'created_triggers';
    static global string SECURE_ENTITY_TYPE = '280240000';
    static global string USER_ATTRIBUTE_TYPE = '280240001';    
    static global string GENERAL_SETTING_TYPE = '280240004';
    static global string OBLIGATION_QUERY_TYPE = '280240005';
    static global string JPC_RSS = 'nxl_jpc';
    static global string CC_RSS = 'nxl_cc';
    static global string NXL_PREFIX = 'Nxl';
}